// See README.md for details
// Switch to Stage1 for the full code
#include ...

// ---- Logging
#define ...
struct Logger ...
Logger NewLogger(std::string name) ...

// ---- Data management
struct DB ...
DB NewDatabase() ...

// ---- User management
struct User ...
User NewUser(DB& db, std::string name) ...

// ---- Application
int main() ...
